version: '3.8'

services:
  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  mysql_data:
  static_files:
  media_files: