# Generated by Django 4.2.7 on 2025-08-25 23:32

from django.db import migrations


def fix_post_slugs(apps, schema_editor):
    """Исправляет проблемы с slug постов"""
    Post = apps.get_model('posts', 'Post')
    
    # Удаляем посты с проблемным slug
    Post.objects.filter(slug='post').delete()
    
    # Исправляем дубликаты slug
    seen_slugs = set()
    for post in Post.objects.all():
        if post.slug in seen_slugs:
            # Генерируем новый уникальный slug
            base_slug = post.slug
            counter = 1
            while f"{base_slug}-{counter}" in seen_slugs:
                counter += 1
            post.slug = f"{base_slug}-{counter}"
            post.save()
        seen_slugs.add(post.slug)


def reverse_fix_post_slugs(apps, schema_editor):
    """Откат изменений (не требуется)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.RunPython(fix_post_slugs, reverse_fix_post_slugs),
    ]
