# Generated by Django 4.2.7 on 2025-08-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20250826_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_enabled',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='post',
            name='can_comment',
            field=models.BooleanField(default=True, verbose_name='Разрешены комментарии'),
        ),
    ]
