# Generated by Django 4.2.7 on 2025-09-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_can_comment_field'),
        ('users', '0005_sharedpost_postarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post', verbose_name='Пост'),
        ),
    ]
