# Generated by Django 4.2.7 on 2025-09-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_chat_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AddField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный чат'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текстовое сообщение'), ('image', 'Изображение'), ('file', 'Файл'), ('voice', 'Голосовое сообщение')], default='text', max_length=10, verbose_name='Тип сообщения'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='users.chatmessage', verbose_name='Ответ на сообщение'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
